defaults:
  - env/train: PickPlaceColorSort
  - env/eval: PickPlaceColorSort
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file:///mnt/RL/yzy/RLinf/examples/embodiment/config/

cluster:
  num_nodes: 1
  component_placement:
    actor: 0-0
    env: 0-0
    rollout: 0-0

runner:
  task_type: embodied
  logger:
    log_path: "/mnt/RL/yzy/recordings/rlinf_logs"
    project_name: maniskill_ppo_color_sort
    experiment_name: "color_sort_clip_mlp"
    logger_backends: ["tensorboard"]

  max_epochs: 1200
  max_steps: -1

  only_eval: False
  val_check_interval: 50
  save_interval: 500
  seq_length: 4096
  max_prompt_length: 30
  
  # 文本prompt配置
  task_prompt: "Please place objects of different colors in separate areas. The specific rule is to put dark-colored items on the right side of the robotic arm and light-colored items on the left side."

algorithm:
  update_epoch: 4
  auto_reset: True
  ignore_terminations: False
  use_fixed_reset_state_ids: False
  normalize_advantages: True
  kl_penalty: kl
  group_size: 1
  n_chunk_steps: 50
  n_eval_chunk_steps: 50
  num_group_envs: 16  # 16个并行环境（进一步减少以避免GPU显存不足）
  rollout_epoch: 1
  reward_type: action_level
  logprob_type: action_level
  entropy_type: action_level

  adv_type: gae
  loss_type: actor_critic
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 1.0
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  sampling_params:
    use_greedy: False
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 0
    top_p: 1.0
    repetition_penalty: 1.0

  length_params:
    max_new_token: 7
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  channel:
    name: "env_buffer_list"
    queue_name: "obs_buffer"
    queue_size: 0
  enable_offload: False

rollout:
  group_name: "RolloutGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "action_buffer"
    queue_size: 0
  mode: "colocate"
  backend: "huggingface"
  model_dir: ""
  enable_offload: False
  pipeline_stage_num: 1
  precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "replay_buffer"
    queue_size: 0
  training_backend: "fsdp"
  checkpoint_load_path: ""
  checkpoint_save_path: "/mnt/RL/yzy/recordings/rlinf_logs/checkpoints"
  micro_batch_size: 160  # 调整为环境数量的10倍（16*10=160）
  global_batch_size: 160
  seed: 1234
  enable_offload: False

  model:
    model_name: "clip_mlp_policy"
    policy_setup: "panda-qpos"
    obs_dim: 45  # 状态维度
    action_dim: 8
    num_action_chunks: 1
    hidden_dim: 256
    
    # CLIP模型配置
    clip_model_name: "ViT-B/32"  # CLIP模型版本
    freeze_clip: True  # 是否冻结CLIP参数
    use_state: True  # 是否使用状态信息
    vision_embed_dim: 512  # CLIP视觉特征维度
    text_embed_dim: 512  # CLIP文本特征维度
    
    precision: "32"
    add_value_head: True
    
    is_lora: False
    lora_rank: 32
    ckpt_path: null
    gradient_checkpointing: False
    sharding_strategy: no_shard

  optim:
    lr: 3.0e-4
    value_lr: 3.0e-4
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-05
    clip_grad: 0.5

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    cpu_offload: False
    offload_pin_memory: False
    reshard_after_forward: True
    enable_gradient_accumulation: True
    forward_prefetch: False
    limit_all_gathers: False
    backward_prefetch: null
    use_orig_params: True  # 设置为True以支持混合requires_grad（冻结的CLIP参数和可训练参数）
    use_liger_kernel: False
    fsdp_size: -1

    mixed_precision:
      param_dtype: "32"  # 使用float32确保所有参数类型一致
      reduce_dtype: "32"
      buffer_dtype: "32"

    amp:
      enabled: False
      precision: "fp32"
      use_grad_scaler: False

reward:
  use_reward_model: False

critic:
  use_critic_model: False

