defaults:
  - env/train: PickPlaceMultiShape
  - env/eval: PickPlaceMultiShape
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file:///mnt/RL/yzy/RLinf/examples/embodiment/config/

cluster:
  num_nodes: 1
  component_placement:
    actor: 0-0
    env: 0-0
    rollout: 0-0

runner:
  task_type: embodied
  logger:
    log_path: "/mnt/RL/yzy/recordings/rlinf_logs"
    project_name: maniskill_ppo_pickplace
    experiment_name: "pickplace_multishape_mlp"
    logger_backends: ["tensorboard"]

  max_epochs: 1200  # 设置为1200 epochs
  max_steps: -1

  only_eval: False
  val_check_interval: 50
  save_interval: 500
  seq_length: 4096
  max_prompt_length: 30

algorithm:
  update_epoch: 4
  auto_reset: True
  ignore_terminations: False
  use_fixed_reset_state_ids: False
  normalize_advantages: True
  kl_penalty: kl
  group_size: 1
  n_chunk_steps: 50
  n_eval_chunk_steps: 50
  num_group_envs: 64  # 设置为64个环境
  rollout_epoch: 1
  reward_type: action_level
  logprob_type: action_level
  entropy_type: action_level

  adv_type: gae
  loss_type: actor_critic
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 1.0
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  sampling_params:
    use_greedy: False
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 0
    top_p: 1.0
    repetition_penalty: 1.0

  length_params:
    max_new_token: 7
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  channel:
    name: "env_buffer_list"
    queue_name: "obs_buffer"
    queue_size: 0
  enable_offload: False

rollout:
  group_name: "RolloutGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "action_buffer"
    queue_size: 0
  mode: "colocate"
  backend: "huggingface"
  model_dir: ""
  enable_offload: False
  pipeline_stage_num: 1
  precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "replay_buffer"
    queue_size: 0
  training_backend: "fsdp"
  checkpoint_load_path: ""
  checkpoint_save_path: "/mnt/RL/yzy/recordings/rlinf_logs/checkpoints"
  micro_batch_size: 320  # 批次大小设置为环境数量的5倍（64*5=320）
  global_batch_size: 320
  seed: 1234
  enable_offload: False

  model:
    model_name: "mlp_policy"
    policy_setup: "panda-qpos"
    obs_dim: 45  # PickSingleYCB环境使用state模式，实际观测维度为45
    action_dim: 8
    num_action_chunks: 1
    hidden_dim: 256
    
    precision: "32"
    add_value_head: True
    
    is_lora: False
    lora_rank: 32
    ckpt_path: null
    gradient_checkpointing: False
    sharding_strategy: no_shard

  optim:
    lr: 3.0e-4
    value_lr: 3.0e-4
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-05
    clip_grad: 0.5

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    cpu_offload: False
    offload_pin_memory: False
    reshard_after_forward: True
    enable_gradient_accumulation: True
    forward_prefetch: False
    limit_all_gathers: False
    backward_prefetch: null
    use_orig_params: False
    use_liger_kernel: False
    fsdp_size: -1

    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

    amp:
      enabled: False
      precision: "fp32"
      use_grad_scaler: False

reward:
  use_reward_model: False

critic:
  use_critic_model: False
